services:
  - type: web
    name: forum-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node forum.js
    envVars:
      - key: NODE_ENV
        value: production
